# Generated by Django 3.1.1 on 2021-04-07 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=25)),
                ('images', models.FileField(upload_to='')),
                ('description', models.TextField()),
                ('date_post', models.DateField(auto_now_add=True)),
                ('categorie', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Service.categorie')),
            ],
        ),
    ]
