# Generated by Django 3.1.1 on 2021-04-08 09:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0003_auto_20210408_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='images',
            field=models.FileField(default=datetime.datetime(2021, 4, 8, 9, 9, 0, 298181, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
