# Generated by Django 3.1.1 on 2021-04-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0004_categorie_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('movie', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('date_pub', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
