# Generated by Django 3.1.1 on 2021-04-08 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0005_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
