# Generated by Django 3.2 on 2021-04-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0006_delete_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='images',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='album',
            name='titre',
            field=models.CharField(max_length=30),
        ),
    ]
