# Generated by Django 3.2 on 2021-04-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0007_auto_20210410_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='urlVideoAccueil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
            ],
        ),
    ]
