# Generated by Django 3.2 on 2021-04-12 10:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0008_urlvideoaccueil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
