# Generated by Django 3.2 on 2021-04-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0009_alter_actualite_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='titre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
