# Generated by Django 3.2 on 2021-04-23 21:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('images', models.FileField(upload_to='annonce')),
                ('date_pub', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
