# Generated by Django 3.2 on 2021-04-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiants', '0003_messageetudiant_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiantsinscrit',
            name='secteur',
            field=models.CharField(max_length=150, verbose_name="secteur d'expertise"),
        ),
    ]
